# Fonts

font-family = "VictorMono Nerd Font"
font-family-bold = "VictorMono Nerd Font"
font-family-italic = "VictorMono Nerd Font"
font-family-bold-italic = "VictorMono Nerd Font"
font-style = "ExtraLight"
font-style-bold = "Bold"
font-style-italic = "ExtraLight Italic"
font-style-bold-italic = "Bold Italic"
font-synthetic-style = 
font-feature =
font-size = 24
font-variation = 
font-variation-bold =
font-variation-italic =
font-variation-bold-italic =
font-codepoint-map =
font-thicken = false
font-thicken-strength =
